# Generated by Django 6.0.2 on 2026-02-19 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL Store')),
                ('myshopify_url', models.URLField(blank=True, verbose_name='URL myshopify.com')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome brand')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Dominio')),
                ('niche', models.CharField(choices=[('arredamento', 'Arredamento & Casa'), ('moda', 'Moda & Abbigliamento'), ('gioielli', 'Gioielli & Accessori'), ('beauty', 'Beauty & Cosmetica'), ('food', 'Food & Beverage'), ('sport', 'Sport & Outdoor'), ('tech', 'Tech & Elettronica'), ('arte', 'Arte & Stampe'), ('bambini', 'Bambini & Giochi'), ('animali', 'Animali'), ('altro', 'Altro')], default='altro', max_length=50)),
                ('status', models.CharField(choices=[('new', 'Nuovo'), ('analyzed', 'Analizzato'), ('contacted', 'Contattato'), ('replied', 'Ha risposto'), ('converted', 'Convertito'), ('rejected', 'Non interessato'), ('skip', 'Da saltare')], default='new', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Tag separati da virgola', max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email principale')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('piva', models.CharField(blank=True, max_length=20, verbose_name='P.IVA')),
                ('address', models.TextField(blank=True, verbose_name='Indirizzo')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scoperto il')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Store',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('manual', 'Manuale (DM/altro)'), ('call', 'Telefonata')], default='email', max_length=20)),
                ('outcome', models.CharField(choices=[('sent', 'Inviato'), ('opened', 'Aperto'), ('replied', 'Risposta ricevuta'), ('interested', 'Interessato'), ('not_now', 'Non ora'), ('rejected', 'Non interessato'), ('bounced', 'Email bounced')], default='sent', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True, verbose_name='Corpo messaggio')),
                ('notes', models.TextField(blank=True, verbose_name='Note follow-up')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='stores.store')),
            ],
            options={
                'verbose_name': 'Log Contatto',
                'verbose_name_plural': 'Log Contatti',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_score', models.IntegerField(default=0, verbose_name='Lead Score')),
                ('lead_priority', models.CharField(blank=True, max_length=20)),
                ('lead_potential', models.CharField(blank=True, max_length=20)),
                ('product_count', models.IntegerField(default=0)),
                ('price_avg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categories', models.CharField(blank=True, max_length=500)),
                ('vendors', models.CharField(blank=True, max_length=500)),
                ('img_quality_score', models.IntegerField(default=0, verbose_name='Score immagini')),
                ('img_total', models.IntegerField(default=0)),
                ('img_avg_per_product', models.FloatField(default=0)),
                ('img_single_count', models.IntegerField(default=0)),
                ('img_low_res_count', models.IntegerField(default=0)),
                ('img_no_alt_count', models.IntegerField(default=0)),
                ('img_issues', models.TextField(blank=True)),
                ('store_title', models.CharField(blank=True, max_length=255)),
                ('store_description', models.TextField(blank=True)),
                ('store_language', models.CharField(blank=True, max_length=10)),
                ('store_theme', models.CharField(blank=True, max_length=50)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_fb_pixel', models.BooleanField(default=False)),
                ('report_file', models.CharField(blank=True, max_length=500, verbose_name='Path report HTML')),
                ('raw_json', models.JSONField(blank=True, null=True, verbose_name='Dati grezzi JSON')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_s', models.IntegerField(default=0, verbose_name='Durata analisi (s)')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='stores.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Analisi Store',
                'verbose_name_plural': 'Analisi Store',
                'ordering': ['-created_at'],
            },
        ),
    ]
