# Generated by Django 6.0.2 on 2026-02-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicheQueryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(choices=[('arredamento', 'Arredamento & Casa'), ('moda', 'Moda & Abbigliamento'), ('gioielli', 'Gioielli & Accessori'), ('beauty', 'Beauty & Cosmetica'), ('food', 'Food & Beverage'), ('sport', 'Sport & Outdoor'), ('tech', 'Tech & Elettronica'), ('arte', 'Arte & Stampe'), ('bambini', 'Bambini & Giochi'), ('animali', 'Animali'), ('altro', 'Altro')], max_length=50, unique=True, verbose_name='Nicchia')),
                ('queries', models.TextField(help_text='Una query per riga. Es: site:myshopify.com arredamento casa italia', verbose_name='Query di ricerca')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Template Query Nicchia',
                'verbose_name_plural': 'Template Query Nicchie',
                'ordering': ['niche'],
            },
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='duration_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeanalysis',
            name='report_file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
