# Generated by Django 6.0.2 on 2026-03-02 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_nichequerytemplate_alter_storeanalysis_duration_s_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es: Freddo - Immagini scarse', max_length=100, verbose_name='Nome template')),
                ('body', models.TextField(help_text='Variabili disponibili: {{ store.name }}, {{ store.domain }}, {{ store.get_niche_display }}', verbose_name='Testo messaggio')),
                ('is_default', models.BooleanField(default=False, help_text='Mostrato automaticamente nella pagina store', verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Messaggio',
                'verbose_name_plural': 'Template Messaggi',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
