# Generated by Django 6.0.2 on 2026-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='whatsapp_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='Popolato anche se il numero non è stato trovato (evita ri-analisi)', null=True, verbose_name='Analisi WhatsApp il'),
        ),
    ]
