# Generated by Django 6.0.2 on 2026-04-07 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_whatsapp_analyzed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Keyword')),
                ('country', models.CharField(default='IT', max_length=10, verbose_name='Paese')),
                ('niche', models.CharField(choices=[('arredamento', 'Arredamento & Casa'), ('moda', 'Moda & Abbigliamento'), ('gioielli', 'Gioielli & Accessori'), ('beauty', 'Beauty & Cosmetica'), ('food', 'Food & Beverage'), ('sport', 'Sport & Outdoor'), ('tech', 'Tech & Elettronica'), ('arte', 'Arte & Stampe'), ('bambini', 'Bambini & Giochi'), ('animali', 'Animali'), ('altro', 'Altro')], default='altro', max_length=50, verbose_name='Nicchia')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Annunci dal')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Annunci fino al')),
                ('shopify_only', models.BooleanField(default=True, verbose_name='Solo Shopify')),
                ('product_ads_only', models.BooleanField(default=False, verbose_name='Solo Product Ads')),
                ('limit', models.IntegerField(default=500, verbose_name='Max annunci')),
                ('status', models.CharField(choices=[('running', 'In corso'), ('completed', 'Completato'), ('error', 'Errore')], default='running', max_length=20, verbose_name='Stato')),
                ('ads_fetched', models.IntegerField(default=0, verbose_name='Annunci scaricati')),
                ('stores_checked', models.IntegerField(default=0, verbose_name='Store verificati')),
                ('stores_new', models.IntegerField(default=0, verbose_name='Store nuovi')),
                ('stores_skipped', models.IntegerField(default=0, verbose_name='Store saltati (già in DB)')),
                ('error_message', models.TextField(blank=True, verbose_name='Errore')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Avviato il')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completato il')),
            ],
            options={
                'verbose_name': 'Ricerca Meta Ads',
                'verbose_name_plural': 'Ricerche Meta Ads',
                'ordering': ['-started_at'],
            },
        ),
    ]
