# Generated by Django 6.0.2 on 2026-04-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_metaadsrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaadsrun',
            name='product_ads_only',
        ),
    ]
