# Generated by Django 6.0.2 on 2026-04-07 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_metaadsrun_product_ads_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdsKeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es: Gioielli Italia, Moda Donna...', max_length=200, verbose_name='Nome lista')),
                ('keywords', models.TextField(help_text='Una keyword per riga. Es: gioielli artigianali', verbose_name='Keywords')),
                ('active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Lista Keyword Meta Ads',
                'verbose_name_plural': 'Liste Keyword Meta Ads',
                'ordering': ['name'],
            },
        ),
    ]
